# Generated by Django 4.1.5 on 2023-01-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
