# Generated by Django 4.1.5 on 2023-01-28 14:17

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='gr_name', max_length=30, verbose_name='Group name')),
                ('group_start', models.DateField(validators=[groups.validators.validate_start_date])),
                ('group_description', models.TextField(blank=True, db_column='gr_descr', null=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
